// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="finn_feeder_chiplet_finn_feeder_chiplet,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.500000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=1744,HLS_SYN_LUT=3217,HLS_VERSION=2023_2}" *)

module finn_feeder_chiplet (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 217'd1;
parameter    ap_ST_fsm_state2 = 217'd2;
parameter    ap_ST_fsm_state3 = 217'd4;
parameter    ap_ST_fsm_state4 = 217'd8;
parameter    ap_ST_fsm_state5 = 217'd16;
parameter    ap_ST_fsm_state6 = 217'd32;
parameter    ap_ST_fsm_state7 = 217'd64;
parameter    ap_ST_fsm_state8 = 217'd128;
parameter    ap_ST_fsm_state9 = 217'd256;
parameter    ap_ST_fsm_state10 = 217'd512;
parameter    ap_ST_fsm_state11 = 217'd1024;
parameter    ap_ST_fsm_state12 = 217'd2048;
parameter    ap_ST_fsm_state13 = 217'd4096;
parameter    ap_ST_fsm_state14 = 217'd8192;
parameter    ap_ST_fsm_state15 = 217'd16384;
parameter    ap_ST_fsm_state16 = 217'd32768;
parameter    ap_ST_fsm_state17 = 217'd65536;
parameter    ap_ST_fsm_state18 = 217'd131072;
parameter    ap_ST_fsm_state19 = 217'd262144;
parameter    ap_ST_fsm_state20 = 217'd524288;
parameter    ap_ST_fsm_state21 = 217'd1048576;
parameter    ap_ST_fsm_state22 = 217'd2097152;
parameter    ap_ST_fsm_state23 = 217'd4194304;
parameter    ap_ST_fsm_state24 = 217'd8388608;
parameter    ap_ST_fsm_state25 = 217'd16777216;
parameter    ap_ST_fsm_state26 = 217'd33554432;
parameter    ap_ST_fsm_state27 = 217'd67108864;
parameter    ap_ST_fsm_state28 = 217'd134217728;
parameter    ap_ST_fsm_state29 = 217'd268435456;
parameter    ap_ST_fsm_state30 = 217'd536870912;
parameter    ap_ST_fsm_state31 = 217'd1073741824;
parameter    ap_ST_fsm_state32 = 217'd2147483648;
parameter    ap_ST_fsm_state33 = 217'd4294967296;
parameter    ap_ST_fsm_state34 = 217'd8589934592;
parameter    ap_ST_fsm_state35 = 217'd17179869184;
parameter    ap_ST_fsm_state36 = 217'd34359738368;
parameter    ap_ST_fsm_state37 = 217'd68719476736;
parameter    ap_ST_fsm_state38 = 217'd137438953472;
parameter    ap_ST_fsm_state39 = 217'd274877906944;
parameter    ap_ST_fsm_state40 = 217'd549755813888;
parameter    ap_ST_fsm_state41 = 217'd1099511627776;
parameter    ap_ST_fsm_state42 = 217'd2199023255552;
parameter    ap_ST_fsm_state43 = 217'd4398046511104;
parameter    ap_ST_fsm_state44 = 217'd8796093022208;
parameter    ap_ST_fsm_state45 = 217'd17592186044416;
parameter    ap_ST_fsm_state46 = 217'd35184372088832;
parameter    ap_ST_fsm_state47 = 217'd70368744177664;
parameter    ap_ST_fsm_state48 = 217'd140737488355328;
parameter    ap_ST_fsm_state49 = 217'd281474976710656;
parameter    ap_ST_fsm_state50 = 217'd562949953421312;
parameter    ap_ST_fsm_state51 = 217'd1125899906842624;
parameter    ap_ST_fsm_state52 = 217'd2251799813685248;
parameter    ap_ST_fsm_state53 = 217'd4503599627370496;
parameter    ap_ST_fsm_state54 = 217'd9007199254740992;
parameter    ap_ST_fsm_state55 = 217'd18014398509481984;
parameter    ap_ST_fsm_state56 = 217'd36028797018963968;
parameter    ap_ST_fsm_state57 = 217'd72057594037927936;
parameter    ap_ST_fsm_state58 = 217'd144115188075855872;
parameter    ap_ST_fsm_state59 = 217'd288230376151711744;
parameter    ap_ST_fsm_state60 = 217'd576460752303423488;
parameter    ap_ST_fsm_state61 = 217'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 217'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 217'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 217'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 217'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 217'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 217'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 217'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 217'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 217'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 217'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 217'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 217'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 217'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 217'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 217'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 217'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 217'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 217'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 217'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 217'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 217'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 217'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 217'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 217'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 217'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 217'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 217'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 217'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 217'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 217'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 217'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 217'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 217'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 217'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 217'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 217'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 217'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 217'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 217'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 217'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 217'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 217'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 217'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 217'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 217'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 217'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 217'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 217'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 217'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 217'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 217'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 217'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 217'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 217'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 217'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 217'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 217'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 217'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 217'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 217'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 217'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 217'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 217'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 217'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 217'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 217'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 217'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 217'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 217'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 217'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 217'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state133 = 217'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state134 = 217'd10889035741470030830827987437816582766592;
parameter    ap_ST_fsm_state135 = 217'd21778071482940061661655974875633165533184;
parameter    ap_ST_fsm_state136 = 217'd43556142965880123323311949751266331066368;
parameter    ap_ST_fsm_state137 = 217'd87112285931760246646623899502532662132736;
parameter    ap_ST_fsm_state138 = 217'd174224571863520493293247799005065324265472;
parameter    ap_ST_fsm_state139 = 217'd348449143727040986586495598010130648530944;
parameter    ap_ST_fsm_state140 = 217'd696898287454081973172991196020261297061888;
parameter    ap_ST_fsm_state141 = 217'd1393796574908163946345982392040522594123776;
parameter    ap_ST_fsm_state142 = 217'd2787593149816327892691964784081045188247552;
parameter    ap_ST_fsm_state143 = 217'd5575186299632655785383929568162090376495104;
parameter    ap_ST_fsm_state144 = 217'd11150372599265311570767859136324180752990208;
parameter    ap_ST_fsm_state145 = 217'd22300745198530623141535718272648361505980416;
parameter    ap_ST_fsm_state146 = 217'd44601490397061246283071436545296723011960832;
parameter    ap_ST_fsm_state147 = 217'd89202980794122492566142873090593446023921664;
parameter    ap_ST_fsm_state148 = 217'd178405961588244985132285746181186892047843328;
parameter    ap_ST_fsm_state149 = 217'd356811923176489970264571492362373784095686656;
parameter    ap_ST_fsm_state150 = 217'd713623846352979940529142984724747568191373312;
parameter    ap_ST_fsm_state151 = 217'd1427247692705959881058285969449495136382746624;
parameter    ap_ST_fsm_state152 = 217'd2854495385411919762116571938898990272765493248;
parameter    ap_ST_fsm_state153 = 217'd5708990770823839524233143877797980545530986496;
parameter    ap_ST_fsm_state154 = 217'd11417981541647679048466287755595961091061972992;
parameter    ap_ST_fsm_state155 = 217'd22835963083295358096932575511191922182123945984;
parameter    ap_ST_fsm_state156 = 217'd45671926166590716193865151022383844364247891968;
parameter    ap_ST_fsm_state157 = 217'd91343852333181432387730302044767688728495783936;
parameter    ap_ST_fsm_state158 = 217'd182687704666362864775460604089535377456991567872;
parameter    ap_ST_fsm_state159 = 217'd365375409332725729550921208179070754913983135744;
parameter    ap_ST_fsm_state160 = 217'd730750818665451459101842416358141509827966271488;
parameter    ap_ST_fsm_state161 = 217'd1461501637330902918203684832716283019655932542976;
parameter    ap_ST_fsm_state162 = 217'd2923003274661805836407369665432566039311865085952;
parameter    ap_ST_fsm_state163 = 217'd5846006549323611672814739330865132078623730171904;
parameter    ap_ST_fsm_state164 = 217'd11692013098647223345629478661730264157247460343808;
parameter    ap_ST_fsm_state165 = 217'd23384026197294446691258957323460528314494920687616;
parameter    ap_ST_fsm_state166 = 217'd46768052394588893382517914646921056628989841375232;
parameter    ap_ST_fsm_state167 = 217'd93536104789177786765035829293842113257979682750464;
parameter    ap_ST_fsm_state168 = 217'd187072209578355573530071658587684226515959365500928;
parameter    ap_ST_fsm_state169 = 217'd374144419156711147060143317175368453031918731001856;
parameter    ap_ST_fsm_state170 = 217'd748288838313422294120286634350736906063837462003712;
parameter    ap_ST_fsm_state171 = 217'd1496577676626844588240573268701473812127674924007424;
parameter    ap_ST_fsm_state172 = 217'd2993155353253689176481146537402947624255349848014848;
parameter    ap_ST_fsm_state173 = 217'd5986310706507378352962293074805895248510699696029696;
parameter    ap_ST_fsm_state174 = 217'd11972621413014756705924586149611790497021399392059392;
parameter    ap_ST_fsm_state175 = 217'd23945242826029513411849172299223580994042798784118784;
parameter    ap_ST_fsm_state176 = 217'd47890485652059026823698344598447161988085597568237568;
parameter    ap_ST_fsm_state177 = 217'd95780971304118053647396689196894323976171195136475136;
parameter    ap_ST_fsm_state178 = 217'd191561942608236107294793378393788647952342390272950272;
parameter    ap_ST_fsm_state179 = 217'd383123885216472214589586756787577295904684780545900544;
parameter    ap_ST_fsm_state180 = 217'd766247770432944429179173513575154591809369561091801088;
parameter    ap_ST_fsm_state181 = 217'd1532495540865888858358347027150309183618739122183602176;
parameter    ap_ST_fsm_state182 = 217'd3064991081731777716716694054300618367237478244367204352;
parameter    ap_ST_fsm_state183 = 217'd6129982163463555433433388108601236734474956488734408704;
parameter    ap_ST_fsm_state184 = 217'd12259964326927110866866776217202473468949912977468817408;
parameter    ap_ST_fsm_state185 = 217'd24519928653854221733733552434404946937899825954937634816;
parameter    ap_ST_fsm_state186 = 217'd49039857307708443467467104868809893875799651909875269632;
parameter    ap_ST_fsm_state187 = 217'd98079714615416886934934209737619787751599303819750539264;
parameter    ap_ST_fsm_state188 = 217'd196159429230833773869868419475239575503198607639501078528;
parameter    ap_ST_fsm_state189 = 217'd392318858461667547739736838950479151006397215279002157056;
parameter    ap_ST_fsm_state190 = 217'd784637716923335095479473677900958302012794430558004314112;
parameter    ap_ST_fsm_state191 = 217'd1569275433846670190958947355801916604025588861116008628224;
parameter    ap_ST_fsm_state192 = 217'd3138550867693340381917894711603833208051177722232017256448;
parameter    ap_ST_fsm_state193 = 217'd6277101735386680763835789423207666416102355444464034512896;
parameter    ap_ST_fsm_state194 = 217'd12554203470773361527671578846415332832204710888928069025792;
parameter    ap_ST_fsm_state195 = 217'd25108406941546723055343157692830665664409421777856138051584;
parameter    ap_ST_fsm_state196 = 217'd50216813883093446110686315385661331328818843555712276103168;
parameter    ap_ST_fsm_state197 = 217'd100433627766186892221372630771322662657637687111424552206336;
parameter    ap_ST_fsm_state198 = 217'd200867255532373784442745261542645325315275374222849104412672;
parameter    ap_ST_fsm_state199 = 217'd401734511064747568885490523085290650630550748445698208825344;
parameter    ap_ST_fsm_state200 = 217'd803469022129495137770981046170581301261101496891396417650688;
parameter    ap_ST_fsm_state201 = 217'd1606938044258990275541962092341162602522202993782792835301376;
parameter    ap_ST_fsm_state202 = 217'd3213876088517980551083924184682325205044405987565585670602752;
parameter    ap_ST_fsm_state203 = 217'd6427752177035961102167848369364650410088811975131171341205504;
parameter    ap_ST_fsm_state204 = 217'd12855504354071922204335696738729300820177623950262342682411008;
parameter    ap_ST_fsm_state205 = 217'd25711008708143844408671393477458601640355247900524685364822016;
parameter    ap_ST_fsm_state206 = 217'd51422017416287688817342786954917203280710495801049370729644032;
parameter    ap_ST_fsm_state207 = 217'd102844034832575377634685573909834406561420991602098741459288064;
parameter    ap_ST_fsm_state208 = 217'd205688069665150755269371147819668813122841983204197482918576128;
parameter    ap_ST_fsm_state209 = 217'd411376139330301510538742295639337626245683966408394965837152256;
parameter    ap_ST_fsm_state210 = 217'd822752278660603021077484591278675252491367932816789931674304512;
parameter    ap_ST_fsm_state211 = 217'd1645504557321206042154969182557350504982735865633579863348609024;
parameter    ap_ST_fsm_state212 = 217'd3291009114642412084309938365114701009965471731267159726697218048;
parameter    ap_ST_fsm_state213 = 217'd6582018229284824168619876730229402019930943462534319453394436096;
parameter    ap_ST_fsm_state214 = 217'd13164036458569648337239753460458804039861886925068638906788872192;
parameter    ap_ST_fsm_state215 = 217'd26328072917139296674479506920917608079723773850137277813577744384;
parameter    ap_ST_fsm_state216 = 217'd52656145834278593348959013841835216159447547700274555627155488768;
parameter    ap_ST_fsm_state217 = 217'd105312291668557186697918027683670432318895095400549111254310977536;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
output  [39:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
input  [7:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [216:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [7:0] predicted_index;
wire   [63:0] ext_mem;
wire   [31:0] initial_address;
wire   [31:0] image_size;
wire  signed [31:0] num_images;
wire   [63:0] done_irq;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state75;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state76;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state144;
wire    ap_CS_fsm_state147;
wire    ap_CS_fsm_state148;
wire    ap_CS_fsm_state216;
reg    in_stream_TDATA_blk_n;
reg    ap_block_state1;
reg   [29:0] tmp_1_reg_388;
wire   [0:0] icmp_ln25_fu_254_p2;
reg   [0:0] icmp_ln25_reg_394;
wire   [0:0] empty_fu_260_p2;
reg   [0:0] empty_reg_399;
reg   [29:0] tmp_reg_404;
reg   [60:0] trunc_ln_reg_409;
wire    ap_CS_fsm_state2;
wire   [31:0] empty_29_fu_319_p3;
reg   [31:0] empty_29_reg_415;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg   [63:0] gmem_WDATA;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [63:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg   [63:0] gmem_addr_1_reg_425;
wire    ap_CS_fsm_state73;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_start;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_done;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_idle;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_ready;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWVALID;
wire   [63:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWADDR;
wire   [0:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWID;
wire   [31:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWLEN;
wire   [2:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWSIZE;
wire   [1:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWBURST;
wire   [1:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWLOCK;
wire   [3:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWCACHE;
wire   [2:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWPROT;
wire   [3:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWQOS;
wire   [3:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWREGION;
wire   [0:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWUSER;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WVALID;
wire   [63:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WDATA;
wire   [7:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WSTRB;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WLAST;
wire   [0:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WID;
wire   [0:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WUSER;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARVALID;
wire   [63:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARADDR;
wire   [0:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARID;
wire   [31:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARLEN;
wire   [2:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARSIZE;
wire   [1:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARBURST;
wire   [1:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARLOCK;
wire   [3:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARCACHE;
wire   [2:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARPROT;
wire   [3:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARQOS;
wire   [3:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARREGION;
wire   [0:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARUSER;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_RREADY;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_BREADY;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_out_stream_TREADY;
wire   [39:0] grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_out_stream_TDATA;
wire    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_out_stream_TVALID;
reg    grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_start_reg;
wire    ap_CS_fsm_state145;
wire    ap_CS_fsm_state146;
wire  signed [63:0] sext_ln25_fu_326_p1;
wire  signed [63:0] sext_ln28_fu_346_p1;
reg    ap_block_state216;
reg   [31:0] indvar_fu_130;
wire   [31:0] add_ln25_1_fu_364_p2;
wire    ap_CS_fsm_state74;
wire   [0:0] icmp_ln25_1_fu_359_p2;
reg   [7:0] predicted_index_preg;
wire   [29:0] mul_ln25_fu_220_p0;
wire   [31:0] mul2_fu_224_p0;
wire   [33:0] mul2_fu_224_p1;
wire   [31:0] mul_fu_229_p0;
wire   [33:0] mul_fu_229_p1;
wire   [64:0] mul_fu_229_p2;
wire  signed [31:0] icmp_ln25_fu_254_p0;
wire   [64:0] mul2_fu_224_p2;
wire   [32:0] shl_ln_fu_285_p3;
wire   [63:0] zext_ln25_fu_292_p1;
wire   [63:0] add_ln25_fu_296_p2;
wire   [31:0] mul_ln25_fu_220_p2;
wire   [31:0] select_ln25_fu_312_p3;
wire   [60:0] trunc_ln1_fu_336_p4;
wire  signed [31:0] icmp_ln25_1_fu_359_p1;
wire    ap_CS_fsm_state217;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [216:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
reg    ap_ST_fsm_state75_blk;
reg    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
wire    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
wire    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
wire    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
wire    ap_ST_fsm_state110_blk;
wire    ap_ST_fsm_state111_blk;
wire    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
wire    ap_ST_fsm_state114_blk;
wire    ap_ST_fsm_state115_blk;
wire    ap_ST_fsm_state116_blk;
wire    ap_ST_fsm_state117_blk;
wire    ap_ST_fsm_state118_blk;
wire    ap_ST_fsm_state119_blk;
wire    ap_ST_fsm_state120_blk;
wire    ap_ST_fsm_state121_blk;
wire    ap_ST_fsm_state122_blk;
wire    ap_ST_fsm_state123_blk;
wire    ap_ST_fsm_state124_blk;
wire    ap_ST_fsm_state125_blk;
wire    ap_ST_fsm_state126_blk;
wire    ap_ST_fsm_state127_blk;
wire    ap_ST_fsm_state128_blk;
wire    ap_ST_fsm_state129_blk;
wire    ap_ST_fsm_state130_blk;
wire    ap_ST_fsm_state131_blk;
wire    ap_ST_fsm_state132_blk;
wire    ap_ST_fsm_state133_blk;
wire    ap_ST_fsm_state134_blk;
wire    ap_ST_fsm_state135_blk;
wire    ap_ST_fsm_state136_blk;
wire    ap_ST_fsm_state137_blk;
wire    ap_ST_fsm_state138_blk;
wire    ap_ST_fsm_state139_blk;
wire    ap_ST_fsm_state140_blk;
wire    ap_ST_fsm_state141_blk;
wire    ap_ST_fsm_state142_blk;
wire    ap_ST_fsm_state143_blk;
reg    ap_ST_fsm_state144_blk;
wire    ap_ST_fsm_state145_blk;
reg    ap_ST_fsm_state146_blk;
reg    ap_ST_fsm_state147_blk;
reg    ap_ST_fsm_state148_blk;
wire    ap_ST_fsm_state149_blk;
wire    ap_ST_fsm_state150_blk;
wire    ap_ST_fsm_state151_blk;
wire    ap_ST_fsm_state152_blk;
wire    ap_ST_fsm_state153_blk;
wire    ap_ST_fsm_state154_blk;
wire    ap_ST_fsm_state155_blk;
wire    ap_ST_fsm_state156_blk;
wire    ap_ST_fsm_state157_blk;
wire    ap_ST_fsm_state158_blk;
wire    ap_ST_fsm_state159_blk;
wire    ap_ST_fsm_state160_blk;
wire    ap_ST_fsm_state161_blk;
wire    ap_ST_fsm_state162_blk;
wire    ap_ST_fsm_state163_blk;
wire    ap_ST_fsm_state164_blk;
wire    ap_ST_fsm_state165_blk;
wire    ap_ST_fsm_state166_blk;
wire    ap_ST_fsm_state167_blk;
wire    ap_ST_fsm_state168_blk;
wire    ap_ST_fsm_state169_blk;
wire    ap_ST_fsm_state170_blk;
wire    ap_ST_fsm_state171_blk;
wire    ap_ST_fsm_state172_blk;
wire    ap_ST_fsm_state173_blk;
wire    ap_ST_fsm_state174_blk;
wire    ap_ST_fsm_state175_blk;
wire    ap_ST_fsm_state176_blk;
wire    ap_ST_fsm_state177_blk;
wire    ap_ST_fsm_state178_blk;
wire    ap_ST_fsm_state179_blk;
wire    ap_ST_fsm_state180_blk;
wire    ap_ST_fsm_state181_blk;
wire    ap_ST_fsm_state182_blk;
wire    ap_ST_fsm_state183_blk;
wire    ap_ST_fsm_state184_blk;
wire    ap_ST_fsm_state185_blk;
wire    ap_ST_fsm_state186_blk;
wire    ap_ST_fsm_state187_blk;
wire    ap_ST_fsm_state188_blk;
wire    ap_ST_fsm_state189_blk;
wire    ap_ST_fsm_state190_blk;
wire    ap_ST_fsm_state191_blk;
wire    ap_ST_fsm_state192_blk;
wire    ap_ST_fsm_state193_blk;
wire    ap_ST_fsm_state194_blk;
wire    ap_ST_fsm_state195_blk;
wire    ap_ST_fsm_state196_blk;
wire    ap_ST_fsm_state197_blk;
wire    ap_ST_fsm_state198_blk;
wire    ap_ST_fsm_state199_blk;
wire    ap_ST_fsm_state200_blk;
wire    ap_ST_fsm_state201_blk;
wire    ap_ST_fsm_state202_blk;
wire    ap_ST_fsm_state203_blk;
wire    ap_ST_fsm_state204_blk;
wire    ap_ST_fsm_state205_blk;
wire    ap_ST_fsm_state206_blk;
wire    ap_ST_fsm_state207_blk;
wire    ap_ST_fsm_state208_blk;
wire    ap_ST_fsm_state209_blk;
wire    ap_ST_fsm_state210_blk;
wire    ap_ST_fsm_state211_blk;
wire    ap_ST_fsm_state212_blk;
wire    ap_ST_fsm_state213_blk;
wire    ap_ST_fsm_state214_blk;
wire    ap_ST_fsm_state215_blk;
reg    ap_ST_fsm_state216_blk;
reg    ap_ST_fsm_state217_blk;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [7:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire   [64:0] mul2_fu_224_p00;
wire   [64:0] mul_fu_229_p00;
wire   [31:0] mul_ln25_fu_220_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 217'd1;
#0 grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_start_reg = 1'b0;
#0 indvar_fu_130 = 32'd0;
#0 predicted_index_preg = 8'd0;
end

finn_feeder_chiplet_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2 grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_start),
    .ap_done(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_done),
    .ap_idle(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_idle),
    .ap_ready(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_ready),
    .m_axi_gmem_AWVALID(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .out_stream_TREADY(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_out_stream_TREADY),
    .trunc_ln28_1(tmp_1_reg_388),
    .sext_ln25(trunc_ln_reg_409),
    .out_stream_TDATA(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_out_stream_TDATA),
    .out_stream_TVALID(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_out_stream_TVALID)
);

finn_feeder_chiplet_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .predicted_index(predicted_index),
    .ext_mem(ext_mem),
    .initial_address(initial_address),
    .image_size(image_size),
    .num_images(num_images),
    .done_irq(done_irq),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

finn_feeder_chiplet_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 64 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_1_reg_425),
    .I_AWLEN(32'd1),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(gmem_WDATA),
    .I_WSTRB(8'd1),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

finn_feeder_chiplet_mul_30ns_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_30ns_32s_32_1_1_U5(
    .din0(mul_ln25_fu_220_p0),
    .din1(num_images),
    .dout(mul_ln25_fu_220_p2)
);

finn_feeder_chiplet_mul_32ns_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32ns_34ns_65_1_1_U6(
    .din0(mul2_fu_224_p0),
    .din1(mul2_fu_224_p1),
    .dout(mul2_fu_224_p2)
);

finn_feeder_chiplet_mul_32ns_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32ns_34ns_65_1_1_U7(
    .din0(mul_fu_229_p0),
    .din1(mul_fu_229_p1),
    .dout(mul_fu_229_p2)
);

finn_feeder_chiplet_regslice_both #(
    .DataWidth( 40 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_out_stream_TDATA),
    .vld_in(grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

finn_feeder_chiplet_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state217))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state145)) begin
            grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_start_reg <= 1'b1;
        end else if ((grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_ready == 1'b1)) begin
            grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        predicted_index_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_state216) & (1'b1 == ap_CS_fsm_state216))) begin
            predicted_index_preg <= in_stream_TDATA_int_regslice;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_fu_130 <= 32'd0;
    end else if (((icmp_ln25_1_fu_359_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state74))) begin
        indvar_fu_130 <= add_ln25_1_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_29_reg_415 <= empty_29_fu_319_p3;
        trunc_ln_reg_409 <= {{add_ln25_fu_296_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_399 <= empty_fu_260_p2;
        icmp_ln25_reg_394 <= icmp_ln25_fu_254_p2;
        tmp_1_reg_388 <= {{mul_fu_229_p2[64:35]}};
        tmp_reg_404 <= {{mul2_fu_224_p2[64:35]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        gmem_addr_1_reg_425 <= sext_ln28_fu_346_p1;
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

assign ap_ST_fsm_state102_blk = 1'b0;

assign ap_ST_fsm_state103_blk = 1'b0;

assign ap_ST_fsm_state104_blk = 1'b0;

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state110_blk = 1'b0;

assign ap_ST_fsm_state111_blk = 1'b0;

assign ap_ST_fsm_state112_blk = 1'b0;

assign ap_ST_fsm_state113_blk = 1'b0;

assign ap_ST_fsm_state114_blk = 1'b0;

assign ap_ST_fsm_state115_blk = 1'b0;

assign ap_ST_fsm_state116_blk = 1'b0;

assign ap_ST_fsm_state117_blk = 1'b0;

assign ap_ST_fsm_state118_blk = 1'b0;

assign ap_ST_fsm_state119_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state120_blk = 1'b0;

assign ap_ST_fsm_state121_blk = 1'b0;

assign ap_ST_fsm_state122_blk = 1'b0;

assign ap_ST_fsm_state123_blk = 1'b0;

assign ap_ST_fsm_state124_blk = 1'b0;

assign ap_ST_fsm_state125_blk = 1'b0;

assign ap_ST_fsm_state126_blk = 1'b0;

assign ap_ST_fsm_state127_blk = 1'b0;

assign ap_ST_fsm_state128_blk = 1'b0;

assign ap_ST_fsm_state129_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state130_blk = 1'b0;

assign ap_ST_fsm_state131_blk = 1'b0;

assign ap_ST_fsm_state132_blk = 1'b0;

assign ap_ST_fsm_state133_blk = 1'b0;

assign ap_ST_fsm_state134_blk = 1'b0;

assign ap_ST_fsm_state135_blk = 1'b0;

assign ap_ST_fsm_state136_blk = 1'b0;

assign ap_ST_fsm_state137_blk = 1'b0;

assign ap_ST_fsm_state138_blk = 1'b0;

assign ap_ST_fsm_state139_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state140_blk = 1'b0;

assign ap_ST_fsm_state141_blk = 1'b0;

assign ap_ST_fsm_state142_blk = 1'b0;

assign ap_ST_fsm_state143_blk = 1'b0;

always @ (*) begin
    if ((gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state144_blk = 1'b1;
    end else begin
        ap_ST_fsm_state144_blk = 1'b0;
    end
end

assign ap_ST_fsm_state145_blk = 1'b0;

always @ (*) begin
    if ((grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_done == 1'b0)) begin
        ap_ST_fsm_state146_blk = 1'b1;
    end else begin
        ap_ST_fsm_state146_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state147_blk = 1'b1;
    end else begin
        ap_ST_fsm_state147_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_WREADY == 1'b0)) begin
        ap_ST_fsm_state148_blk = 1'b1;
    end else begin
        ap_ST_fsm_state148_blk = 1'b0;
    end
end

assign ap_ST_fsm_state149_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state150_blk = 1'b0;

assign ap_ST_fsm_state151_blk = 1'b0;

assign ap_ST_fsm_state152_blk = 1'b0;

assign ap_ST_fsm_state153_blk = 1'b0;

assign ap_ST_fsm_state154_blk = 1'b0;

assign ap_ST_fsm_state155_blk = 1'b0;

assign ap_ST_fsm_state156_blk = 1'b0;

assign ap_ST_fsm_state157_blk = 1'b0;

assign ap_ST_fsm_state158_blk = 1'b0;

assign ap_ST_fsm_state159_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state160_blk = 1'b0;

assign ap_ST_fsm_state161_blk = 1'b0;

assign ap_ST_fsm_state162_blk = 1'b0;

assign ap_ST_fsm_state163_blk = 1'b0;

assign ap_ST_fsm_state164_blk = 1'b0;

assign ap_ST_fsm_state165_blk = 1'b0;

assign ap_ST_fsm_state166_blk = 1'b0;

assign ap_ST_fsm_state167_blk = 1'b0;

assign ap_ST_fsm_state168_blk = 1'b0;

assign ap_ST_fsm_state169_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state170_blk = 1'b0;

assign ap_ST_fsm_state171_blk = 1'b0;

assign ap_ST_fsm_state172_blk = 1'b0;

assign ap_ST_fsm_state173_blk = 1'b0;

assign ap_ST_fsm_state174_blk = 1'b0;

assign ap_ST_fsm_state175_blk = 1'b0;

assign ap_ST_fsm_state176_blk = 1'b0;

assign ap_ST_fsm_state177_blk = 1'b0;

assign ap_ST_fsm_state178_blk = 1'b0;

assign ap_ST_fsm_state179_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state180_blk = 1'b0;

assign ap_ST_fsm_state181_blk = 1'b0;

assign ap_ST_fsm_state182_blk = 1'b0;

assign ap_ST_fsm_state183_blk = 1'b0;

assign ap_ST_fsm_state184_blk = 1'b0;

assign ap_ST_fsm_state185_blk = 1'b0;

assign ap_ST_fsm_state186_blk = 1'b0;

assign ap_ST_fsm_state187_blk = 1'b0;

assign ap_ST_fsm_state188_blk = 1'b0;

assign ap_ST_fsm_state189_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state190_blk = 1'b0;

assign ap_ST_fsm_state191_blk = 1'b0;

assign ap_ST_fsm_state192_blk = 1'b0;

assign ap_ST_fsm_state193_blk = 1'b0;

assign ap_ST_fsm_state194_blk = 1'b0;

assign ap_ST_fsm_state195_blk = 1'b0;

assign ap_ST_fsm_state196_blk = 1'b0;

assign ap_ST_fsm_state197_blk = 1'b0;

assign ap_ST_fsm_state198_blk = 1'b0;

assign ap_ST_fsm_state199_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state200_blk = 1'b0;

assign ap_ST_fsm_state201_blk = 1'b0;

assign ap_ST_fsm_state202_blk = 1'b0;

assign ap_ST_fsm_state203_blk = 1'b0;

assign ap_ST_fsm_state204_blk = 1'b0;

assign ap_ST_fsm_state205_blk = 1'b0;

assign ap_ST_fsm_state206_blk = 1'b0;

assign ap_ST_fsm_state207_blk = 1'b0;

assign ap_ST_fsm_state208_blk = 1'b0;

assign ap_ST_fsm_state209_blk = 1'b0;

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state210_blk = 1'b0;

assign ap_ST_fsm_state211_blk = 1'b0;

assign ap_ST_fsm_state212_blk = 1'b0;

assign ap_ST_fsm_state213_blk = 1'b0;

assign ap_ST_fsm_state214_blk = 1'b0;

assign ap_ST_fsm_state215_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state216)) begin
        ap_ST_fsm_state216_blk = 1'b1;
    end else begin
        ap_ST_fsm_state216_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state217_blk = 1'b1;
    end else begin
        ap_ST_fsm_state217_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

always @ (*) begin
    if ((gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state75_blk = 1'b1;
    end else begin
        ap_ST_fsm_state75_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_WREADY == 1'b0)) begin
        ap_ST_fsm_state76_blk = 1'b1;
    end else begin
        ap_ST_fsm_state76_blk = 1'b0;
    end
end

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

assign ap_ST_fsm_state96_blk = 1'b0;

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state217))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state217))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARADDR = sext_ln25_fu_326_p1;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARADDR = grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARLEN = empty_29_reg_415;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARLEN = grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARVALID = grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state147)) | ((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75)))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state216) & (1'b1 == ap_CS_fsm_state216)) | ((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state144)))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_RREADY = grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state148)) begin
        gmem_WDATA = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state76)) begin
        gmem_WDATA = 64'd0;
    end else begin
        gmem_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state148)) | ((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state76)))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state147) | (1'b1 == ap_CS_fsm_state75))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state216) | (1'b1 == ap_CS_fsm_state144))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state148) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state216)) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state216) & (1'b1 == ap_CS_fsm_state216))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state216) & (1'b1 == ap_CS_fsm_state216))) begin
        predicted_index = in_stream_TDATA_int_regslice;
    end else begin
        predicted_index = predicted_index_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            if (((icmp_ln25_1_fu_359_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
                ap_NS_fsm = ap_ST_fsm_state217;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end
        end
        ap_ST_fsm_state75 : begin
            if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75))) begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end
        end
        ap_ST_fsm_state76 : begin
            if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            ap_NS_fsm = ap_ST_fsm_state135;
        end
        ap_ST_fsm_state135 : begin
            ap_NS_fsm = ap_ST_fsm_state136;
        end
        ap_ST_fsm_state136 : begin
            ap_NS_fsm = ap_ST_fsm_state137;
        end
        ap_ST_fsm_state137 : begin
            ap_NS_fsm = ap_ST_fsm_state138;
        end
        ap_ST_fsm_state138 : begin
            ap_NS_fsm = ap_ST_fsm_state139;
        end
        ap_ST_fsm_state139 : begin
            ap_NS_fsm = ap_ST_fsm_state140;
        end
        ap_ST_fsm_state140 : begin
            ap_NS_fsm = ap_ST_fsm_state141;
        end
        ap_ST_fsm_state141 : begin
            ap_NS_fsm = ap_ST_fsm_state142;
        end
        ap_ST_fsm_state142 : begin
            ap_NS_fsm = ap_ST_fsm_state143;
        end
        ap_ST_fsm_state143 : begin
            ap_NS_fsm = ap_ST_fsm_state144;
        end
        ap_ST_fsm_state144 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state144))) begin
                ap_NS_fsm = ap_ST_fsm_state145;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state144;
            end
        end
        ap_ST_fsm_state145 : begin
            ap_NS_fsm = ap_ST_fsm_state146;
        end
        ap_ST_fsm_state146 : begin
            if (((grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state146))) begin
                ap_NS_fsm = ap_ST_fsm_state147;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state146;
            end
        end
        ap_ST_fsm_state147 : begin
            if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state147))) begin
                ap_NS_fsm = ap_ST_fsm_state148;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state147;
            end
        end
        ap_ST_fsm_state148 : begin
            if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state148))) begin
                ap_NS_fsm = ap_ST_fsm_state149;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state148;
            end
        end
        ap_ST_fsm_state149 : begin
            ap_NS_fsm = ap_ST_fsm_state150;
        end
        ap_ST_fsm_state150 : begin
            ap_NS_fsm = ap_ST_fsm_state151;
        end
        ap_ST_fsm_state151 : begin
            ap_NS_fsm = ap_ST_fsm_state152;
        end
        ap_ST_fsm_state152 : begin
            ap_NS_fsm = ap_ST_fsm_state153;
        end
        ap_ST_fsm_state153 : begin
            ap_NS_fsm = ap_ST_fsm_state154;
        end
        ap_ST_fsm_state154 : begin
            ap_NS_fsm = ap_ST_fsm_state155;
        end
        ap_ST_fsm_state155 : begin
            ap_NS_fsm = ap_ST_fsm_state156;
        end
        ap_ST_fsm_state156 : begin
            ap_NS_fsm = ap_ST_fsm_state157;
        end
        ap_ST_fsm_state157 : begin
            ap_NS_fsm = ap_ST_fsm_state158;
        end
        ap_ST_fsm_state158 : begin
            ap_NS_fsm = ap_ST_fsm_state159;
        end
        ap_ST_fsm_state159 : begin
            ap_NS_fsm = ap_ST_fsm_state160;
        end
        ap_ST_fsm_state160 : begin
            ap_NS_fsm = ap_ST_fsm_state161;
        end
        ap_ST_fsm_state161 : begin
            ap_NS_fsm = ap_ST_fsm_state162;
        end
        ap_ST_fsm_state162 : begin
            ap_NS_fsm = ap_ST_fsm_state163;
        end
        ap_ST_fsm_state163 : begin
            ap_NS_fsm = ap_ST_fsm_state164;
        end
        ap_ST_fsm_state164 : begin
            ap_NS_fsm = ap_ST_fsm_state165;
        end
        ap_ST_fsm_state165 : begin
            ap_NS_fsm = ap_ST_fsm_state166;
        end
        ap_ST_fsm_state166 : begin
            ap_NS_fsm = ap_ST_fsm_state167;
        end
        ap_ST_fsm_state167 : begin
            ap_NS_fsm = ap_ST_fsm_state168;
        end
        ap_ST_fsm_state168 : begin
            ap_NS_fsm = ap_ST_fsm_state169;
        end
        ap_ST_fsm_state169 : begin
            ap_NS_fsm = ap_ST_fsm_state170;
        end
        ap_ST_fsm_state170 : begin
            ap_NS_fsm = ap_ST_fsm_state171;
        end
        ap_ST_fsm_state171 : begin
            ap_NS_fsm = ap_ST_fsm_state172;
        end
        ap_ST_fsm_state172 : begin
            ap_NS_fsm = ap_ST_fsm_state173;
        end
        ap_ST_fsm_state173 : begin
            ap_NS_fsm = ap_ST_fsm_state174;
        end
        ap_ST_fsm_state174 : begin
            ap_NS_fsm = ap_ST_fsm_state175;
        end
        ap_ST_fsm_state175 : begin
            ap_NS_fsm = ap_ST_fsm_state176;
        end
        ap_ST_fsm_state176 : begin
            ap_NS_fsm = ap_ST_fsm_state177;
        end
        ap_ST_fsm_state177 : begin
            ap_NS_fsm = ap_ST_fsm_state178;
        end
        ap_ST_fsm_state178 : begin
            ap_NS_fsm = ap_ST_fsm_state179;
        end
        ap_ST_fsm_state179 : begin
            ap_NS_fsm = ap_ST_fsm_state180;
        end
        ap_ST_fsm_state180 : begin
            ap_NS_fsm = ap_ST_fsm_state181;
        end
        ap_ST_fsm_state181 : begin
            ap_NS_fsm = ap_ST_fsm_state182;
        end
        ap_ST_fsm_state182 : begin
            ap_NS_fsm = ap_ST_fsm_state183;
        end
        ap_ST_fsm_state183 : begin
            ap_NS_fsm = ap_ST_fsm_state184;
        end
        ap_ST_fsm_state184 : begin
            ap_NS_fsm = ap_ST_fsm_state185;
        end
        ap_ST_fsm_state185 : begin
            ap_NS_fsm = ap_ST_fsm_state186;
        end
        ap_ST_fsm_state186 : begin
            ap_NS_fsm = ap_ST_fsm_state187;
        end
        ap_ST_fsm_state187 : begin
            ap_NS_fsm = ap_ST_fsm_state188;
        end
        ap_ST_fsm_state188 : begin
            ap_NS_fsm = ap_ST_fsm_state189;
        end
        ap_ST_fsm_state189 : begin
            ap_NS_fsm = ap_ST_fsm_state190;
        end
        ap_ST_fsm_state190 : begin
            ap_NS_fsm = ap_ST_fsm_state191;
        end
        ap_ST_fsm_state191 : begin
            ap_NS_fsm = ap_ST_fsm_state192;
        end
        ap_ST_fsm_state192 : begin
            ap_NS_fsm = ap_ST_fsm_state193;
        end
        ap_ST_fsm_state193 : begin
            ap_NS_fsm = ap_ST_fsm_state194;
        end
        ap_ST_fsm_state194 : begin
            ap_NS_fsm = ap_ST_fsm_state195;
        end
        ap_ST_fsm_state195 : begin
            ap_NS_fsm = ap_ST_fsm_state196;
        end
        ap_ST_fsm_state196 : begin
            ap_NS_fsm = ap_ST_fsm_state197;
        end
        ap_ST_fsm_state197 : begin
            ap_NS_fsm = ap_ST_fsm_state198;
        end
        ap_ST_fsm_state198 : begin
            ap_NS_fsm = ap_ST_fsm_state199;
        end
        ap_ST_fsm_state199 : begin
            ap_NS_fsm = ap_ST_fsm_state200;
        end
        ap_ST_fsm_state200 : begin
            ap_NS_fsm = ap_ST_fsm_state201;
        end
        ap_ST_fsm_state201 : begin
            ap_NS_fsm = ap_ST_fsm_state202;
        end
        ap_ST_fsm_state202 : begin
            ap_NS_fsm = ap_ST_fsm_state203;
        end
        ap_ST_fsm_state203 : begin
            ap_NS_fsm = ap_ST_fsm_state204;
        end
        ap_ST_fsm_state204 : begin
            ap_NS_fsm = ap_ST_fsm_state205;
        end
        ap_ST_fsm_state205 : begin
            ap_NS_fsm = ap_ST_fsm_state206;
        end
        ap_ST_fsm_state206 : begin
            ap_NS_fsm = ap_ST_fsm_state207;
        end
        ap_ST_fsm_state207 : begin
            ap_NS_fsm = ap_ST_fsm_state208;
        end
        ap_ST_fsm_state208 : begin
            ap_NS_fsm = ap_ST_fsm_state209;
        end
        ap_ST_fsm_state209 : begin
            ap_NS_fsm = ap_ST_fsm_state210;
        end
        ap_ST_fsm_state210 : begin
            ap_NS_fsm = ap_ST_fsm_state211;
        end
        ap_ST_fsm_state211 : begin
            ap_NS_fsm = ap_ST_fsm_state212;
        end
        ap_ST_fsm_state212 : begin
            ap_NS_fsm = ap_ST_fsm_state213;
        end
        ap_ST_fsm_state213 : begin
            ap_NS_fsm = ap_ST_fsm_state214;
        end
        ap_ST_fsm_state214 : begin
            ap_NS_fsm = ap_ST_fsm_state215;
        end
        ap_ST_fsm_state215 : begin
            ap_NS_fsm = ap_ST_fsm_state216;
        end
        ap_ST_fsm_state216 : begin
            if (((1'b0 == ap_block_state216) & (1'b1 == ap_CS_fsm_state216))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state216;
            end
        end
        ap_ST_fsm_state217 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state217))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state217;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln25_1_fu_364_p2 = (indvar_fu_130 + 32'd1);

assign add_ln25_fu_296_p2 = (zext_ln25_fu_292_p1 + ext_mem);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state144 = ap_CS_fsm[32'd143];

assign ap_CS_fsm_state145 = ap_CS_fsm[32'd144];

assign ap_CS_fsm_state146 = ap_CS_fsm[32'd145];

assign ap_CS_fsm_state147 = ap_CS_fsm[32'd146];

assign ap_CS_fsm_state148 = ap_CS_fsm[32'd147];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state216 = ap_CS_fsm[32'd215];

assign ap_CS_fsm_state217 = ap_CS_fsm[32'd216];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state216 = ((gmem_BVALID == 1'b0) | (in_stream_TVALID_int_regslice == 1'b0));
end

assign empty_29_fu_319_p3 = ((icmp_ln25_reg_394[0:0] == 1'b1) ? select_ln25_fu_312_p3 : 32'd0);

assign empty_fu_260_p2 = ((image_size > 32'd4) ? 1'b1 : 1'b0);

assign grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_start = grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_ap_start_reg;

assign grp_finn_feeder_chiplet_Pipeline_VITIS_LOOP_32_2_fu_210_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state146);

assign icmp_ln25_1_fu_359_p1 = num_images;

assign icmp_ln25_1_fu_359_p2 = ((indvar_fu_130 == icmp_ln25_1_fu_359_p1) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_254_p0 = num_images;

assign icmp_ln25_fu_254_p2 = ((icmp_ln25_fu_254_p0 != 32'd0) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign mul2_fu_224_p0 = mul2_fu_224_p00;

assign mul2_fu_224_p00 = initial_address;

assign mul2_fu_224_p1 = 65'd6871947674;

assign mul_fu_229_p0 = mul_fu_229_p00;

assign mul_fu_229_p00 = image_size;

assign mul_fu_229_p1 = 65'd6871947674;

assign mul_ln25_fu_220_p0 = mul_ln25_fu_220_p00;

assign mul_ln25_fu_220_p00 = tmp_1_reg_388;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign select_ln25_fu_312_p3 = ((empty_reg_399[0:0] == 1'b1) ? mul_ln25_fu_220_p2 : 32'd0);

assign sext_ln25_fu_326_p1 = $signed(trunc_ln_reg_409);

assign sext_ln28_fu_346_p1 = $signed(trunc_ln1_fu_336_p4);

assign shl_ln_fu_285_p3 = {{tmp_reg_404}, {3'd0}};

assign trunc_ln1_fu_336_p4 = {{done_irq[63:3]}};

assign zext_ln25_fu_292_p1 = shl_ln_fu_285_p3;

endmodule //finn_feeder_chiplet
